= Latest Bootstrap Documentation Redirect (Foxified)
:author_1: David Wolf
:email_1: david@wolf.gdn
:author_2: Cameron Peterson
:email_2: kodi@kodirex.space
:icons: font
:bootstrap-version: v5.4

+++
<p align=center>
    <img src="./images/bootstrap.svg" alt="Bootstrap" width="64" height="64">
</p>
+++

NOTE: This is a modified version of David Wolf's extension for Chrome based browsers with compatibility for Firefox, not much needed to be done to work with the advent of the 'WebExtensions' api.

Firefox browser extension to redirect all requests to Bootstrap documentation of versions lower than {bootstrap-version} to the docs of Bootstrap {bootstrap-version}.

For example if you wound up on a documentation page of Bootstrap v4.0, you will be redirected to the documentation of Bootstrap {bootstrap-version}.

== Permission justifications
=== webRequest justification
`webRequest` is needed to check if the requested URL is requesting an outdated Bootstrap documentation page, and to be able to redirect those requests.

=== webRequestBlocking justification
`webRequestBlocking` is needed to make the request synchronous to be able to redirect it.

=== Host permission justification
`\*://getbootstrap.com/docs/*` is needed, as this is the documentation host of Bootstrap. We need to be able to access pages at this url to redirect them.

=== Storage permission justification
`storage` is needed to keep the version of bootstrap to redirect to, as configured in extension settings.

'''

Icon credits to https://icons.getbootstrap.com[Bootstrap Icons].
